### ISSUE TITLE
[iOS] 모델 구현 및 로그 뷰 구현

### ISSUE THREAD

**Issue by Hansolkkim** [OceanShape/todo-list#11]
## 💡 issue
- Card에 사용될 모델 구현
- 로그 뷰 구현
## 📝 todo
- [x] Card 모델로 사용할 객체 구현
  - [x] Card 모델에서 사용될 ID, Caption 타입 구현
  - [x] CardListViewController와 연결될 최상위 모듈 `CardManager` 구현
  - [x] CardListView의 `+`버튼을 누르면 새로운 카드가 추가되는 기능 추가
- [x] 로그 뷰 추가
  - [x] Log 모델 추가
  - [x] Log list와 cell 구현(xib)
  - [x] 열기/닫기 버튼 기능 구현
