### ISSUE TITLE
[iOS] 1주차 2번째 PR 코드리뷰 반영

### ISSUE THREAD

**Issue by Hansolkkim** [OceanShape/todo-list#15]
## 💡 issue
- [코드 리뷰](https://github.com/codesquad-members-2022/todo-list/pull/91) 내용 반영하기
## 📝 todo
- [x] `countBadgeLabel.text` 설정하는 부분을 섹션 row 갯수 정하는 메서드로부터 분리
- [x] 접근제어자 확인하고 수정
- [x] CardFactory의 역할을 알 수 있도록 수정
  - [x] Card의 추상타입 구현
- [x] Card의 데이터 구조 수정
- [x] CardListTableViewCell의 각 요소를 처리하는 하나의 메서드 만들기
- [x] CardManager의 추상타입 구현하여, CardListViewController 초기화시 cardManager 프로퍼티에 의존성 주입하도록 수정
