### ISSUE TITLE
[BE] Card 기능 리팩토링 및 테이블 수정

### ISSUE THREAD

**Issue by ffinn92** [OceanShape/todo-list#16]
## 💡 issue
- Card 기능을 리팩토링하고 Card table을 수정한다.
## 📝 todo
- [x] Card table column 네이밍 수정
- [x] Card domain 네이밍 수정
- [x] Card Update 기능 추가
- [x] Card Move 기능 추가
- [x] Card DTO 수정
- [ ] Card 단위기능 테스트 추가
