### ISSUE TITLE
[iOS] 네트워크 객체 구현하기

### ISSUE THREAD

**Issue by Hansolkkim** [OceanShape/todo-list#18]
## 💡 issue
- 서버와 통신할 수 있는 네트워크 객체 구현하기
## 📝 todo
- [x] `NetworkManager` 객체 구현
  - [x] 데이터를 주고 받을 때 어떤걸 주고 받을지 생각해서 URLRequest 구현 (indexOrder, id, sectionID, title, body, caption)
  - [x] 데이터를 보내기 전 데이터 만드는 로직 구현
