### ISSUE TITLE
[iOS] 터치이벤트 구현

### ISSUE THREAD

**Issue by Hansolkkim** [OceanShape/todo-list#19]
## 💡 issue
- 터치 이벤트 구현
## 📝 todo
- [x] 스와이프해서 셀 제거 기능 구현
  - [x] 입출력 흐름 분리해서 구현하기
- [ ] 롱 프레스 이벤트 구현
- [x] 카드 리스트 컬럼간 Cell 이동 구현
